### PR TITLE
Rename C3W3_Assignment.ipynb to C3_W3_Assignment.ipynb

### PR DESCRIPTION
**Pull request by thatgeeman**
To fix the broken link in the C3 W3 ungraded assignment the file has to be renamed.

The link in the course points to https://github.com/https-deeplearning-ai/tensorflow-1-public/blob/master/C3/W3/assignment/C3_W3_Assignment.ipynb.

### CODE REVIEW

**Comment by andres-zartab** [comment]
Hi @thatgeeman, in which item of the course does the link appear? That file cannot be renamed but I can fix the link.

**Comment by thatgeeman** [comment]
Hi! Alright, the link appears in the "Open tool" button in the "Optional Assignment- Exploring overfitting in NLP" of Course 3 Week 3.

**Comment by andres-zartab** [comment]
Oh I see. That item is deprecated and it should not appear on the most recent version of the course. You are probably enrolled in the old version.

If you would like to update to the new material, [reset your deadlines](https://learner.coursera.help/hc/articles/208279866-Assignment-deadlines). If you’re in the middle of a course, you will lose your notebook work when you reset your deadlines. Please save your work by downloading your existing notebooks before switching to the new version.
Don’t see the option to reset deadlines, or are getting this error message in the assignments: “Your assignment hasn’t been submitted.”
Please contact Coursera via the [Learner Help Center](https://www.coursera.support/s/learner-help-center-contact-us) and ask them to unenroll you, then immediately re-enroll you in the course.
Here are some template messages you can put in the Description of issue field in the Help Center form:
If you still see your old notebooks and the assignments show TF version 1.14:
Hi! A new version of Introduction to TensorFlow for AI, ML, and DL by DeepLearning.AI was recently launched, but it seems I am still actively subscribed to the old session. Please unenroll, then immediately re-enroll me to the latest version of the course so I can see the updated materials and continue my coursework. Thank you!

If you have TF version 2.7 in the assignments but cannot submit it:
Hi! A new version of Introduction to TensorFlow for AI, ML, and DL by DeepLearning.AI was recently launched, but I cannot submit my assignments. I get this error in Coursera Labs: “Your assignment hasn’t been submitted.” Please unenroll, then immediately re-enroll me to the latest version of the course so I can try again. This has worked for other learners in previous courses. Thank you!

Again, remember to download your assignment notebooks first if you’ve already done them. Switching sessions will give you a blank workspace, so you won’t be able to see your previous notebooks.

**Comment by cfav-dev** [comment]
Hi @thatgeeman ! Just to add, the course was recently updated and you may want to switch to that version. We have now placed a note about it in the course and you can also see the [announcement](https://community.deeplearning.ai/t/staff-announcement-course-3-has-been-updated/108834) in Discourse. It contains the details about the refresh and how to switch sessions as Andres pointed above. Hope this helps and sorry for the confusion!

**Comment by thatgeeman** [comment]
Thanks for your replies! Yup, I'll consider switching to the newer version :)

**Pull request closed without merging**
